### ISSUE TITLE
Only checks for groupifier / AGE for imports

### ISSUE THREAD

**Issue by coder13** [Goosly/AGE#31]
This isn't a bug, I see it in the code.

But I don't see why it's necessary. Shouldn't all you need to do is check if any competitors have assignments and begin importing from there?

I'm developing [my own groups software](https://github.com/coder13/delegatedashboard) and I wanted to test if I could view the groups I generated with it in other software and noticed the restriction.

**Comment by Goosly** [comment]
Thanks for letting me know. Apparently I had decided the logic should be "there are assignments from AGE or Groupifier and at least half the competitors have one assignment" more than 2 years ago, for lack of a better idea at that time.
I've now updated it to only the latter part. Can you try again an let me know if you need further changes?

**Comment by coder13** [comment]
It works btw.
