### ISSUE TITLE
Support for printing scorecards with "stage" (room name) on them

### ISSUE THREAD

**Issue by coder13** [Goosly/AGE#33]
I can try to do this if you can't find time but this would be super useful as I've been using the rooms feature to split people up by stage lately.

**Comment by Goosly** [comment]
@coder13 Do you have a suggestion for _where_ on the scorecard you want to see the room name?
I will make this optional since most competitions only use one room - in those cases it seems redundant info.

**Comment by coder13** [comment]
Could go on the group line.

"Round 1 | Group 2 of 3 on Stage X"

**Comment by coder13** [comment]
Most competitions do only use 1 room, but as comps grow, they split the room into stages and I've started using these different stages as different WCIF "rooms" in the same venue.
